// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI7y2OXB7pmgVZwXxQJzerDU_-RfuWYIs',
    appId: '1:695306609058:web:97ad817af13fbb2423d2fb',
    messagingSenderId: '695306609058',
    projectId: 'voicelocal-c43f0',
    authDomain: 'voicelocal-c43f0.firebaseapp.com',
    storageBucket: 'voicelocal-c43f0.firebasestorage.app',
    measurementId: 'G-TY66WW10EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq1G4-jYC2B6kAbDYw9dRHD-48nCP97KQ',
    appId: '1:695306609058:android:213b6e388dde7c3f23d2fb',
    messagingSenderId: '695306609058',
    projectId: 'voicelocal-c43f0',
    storageBucket: 'voicelocal-c43f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC55CtSsDEHZVI6Rz8NELHOu8W4WN-Ud-w',
    appId: '1:695306609058:ios:6287f29461bc499723d2fb',
    messagingSenderId: '695306609058',
    projectId: 'voicelocal-c43f0',
    storageBucket: 'voicelocal-c43f0.firebasestorage.app',
    iosBundleId: 'com.example.voicelocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC55CtSsDEHZVI6Rz8NELHOu8W4WN-Ud-w',
    appId: '1:695306609058:ios:6287f29461bc499723d2fb',
    messagingSenderId: '695306609058',
    projectId: 'voicelocal-c43f0',
    storageBucket: 'voicelocal-c43f0.firebasestorage.app',
    iosBundleId: 'com.example.voicelocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI7y2OXB7pmgVZwXxQJzerDU_-RfuWYIs',
    appId: '1:695306609058:web:aa8dd5eb07810ba423d2fb',
    messagingSenderId: '695306609058',
    projectId: 'voicelocal-c43f0',
    authDomain: 'voicelocal-c43f0.firebaseapp.com',
    storageBucket: 'voicelocal-c43f0.firebasestorage.app',
    measurementId: 'G-L1M62LBS6T',
  );
}
